[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'vim-scripts/TaskList.vim'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'google/vim-colorscheme-primary'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'kevinw/pyflakes-vim'

[[plugins]]
repo = 'hdima/python-syntax'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'benmills/vim-golang-alternate'

[[plugins]]
repo = 'vim-jp/vim-go-extra'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'rust-lang/rust.vim'
